package com.example.marpos.menuitem;

public enum MenuType {
    CHICKEN, BEEF, PORK, SEAFOOD, VEGETABLES, SOUP, DESSERTS, BILAO, PLATTERS, FOODTRAYS, BBQ, PICAPICA, NOODLES, RICE, SIZZLING, DRINKS, HANDAAN
}
