package com.example.marpos.enumeration;

public enum ItemType {
    CHICKEN, BEEF, PORK, SEAFOOD, VEGETABLES, SOUP, DESSERTS, BILAO, PLATTERS, FOODTRAYS, BBQ, PICAPICA, NOODLES, RICE, SIZZLING, DRINKS, HANDAAN
}
